"""V0 imports classifications audit rules and model versions"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '03e12f220861'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_bank', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_bank', 'file_hash')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_example_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('set_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('historical_consistency', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_source'), 'rules', ['source'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('source_bank', sa.String(length=40), nullable=False),
    sa.Column('bank_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('concept_raw', sa.String(), nullable=False),
    sa.Column('concept_key', sa.String(), nullable=False),
    sa.Column('description_raw', sa.String(), nullable=False),
    sa.Column('bank_category', sa.String(), nullable=False),
    sa.Column('bank_type', sa.String(), nullable=False),
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('counterparty_iban', sa.String(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('mcc', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', 'occurrence')
    )
    op.create_index(op.f('ix_transactions_bank_date'), 'transactions', ['bank_date'], unique=False)
    op.create_index(op.f('ix_transactions_concept_key'), 'transactions', ['concept_key'], unique=False)
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_source_bank'), 'transactions', ['source_bank'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_classifications_confirmed_by_user'), 'classifications', ['confirmed_by_user'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=10), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('predicted_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_transaction_id'), 'predictions', ['transaction_id'], unique=False)
    op.create_table('transaction_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('source_bank', sa.String(length=40), nullable=False),
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_bank', 'account_ref', 'external_id')
    )
    op.create_index(op.f('ix_transaction_components_transaction_id'), 'transaction_components', ['transaction_id'], unique=False)
    op.create_table('training_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('classification_id', sa.String(length=36), nullable=True),
    sa.Column('external_key', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prediction_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('final_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('dataset_split', sa.String(length=20), nullable=False),
    sa.Column('sample_weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    op.create_index(op.f('ix_training_examples_transaction_id'), 'training_examples', ['transaction_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_examples_transaction_id'), table_name='training_examples')
    op.drop_table('training_examples')
    op.drop_index(op.f('ix_transaction_components_transaction_id'), table_name='transaction_components')
    op.drop_table('transaction_components')
    op.drop_index(op.f('ix_predictions_transaction_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_classifications_confirmed_by_user'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_transactions_source_bank'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_concept_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bank_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_rules_source'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('model_versions')
    op.drop_table('imports')
    # ### end Alembic commands ###
