"""Separate original historical labels and bank reconciliation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '20273f0f64ef'
down_revision = '03e12f220861'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_sheet', sa.String(length=100), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('source_bank', sa.String(length=40), nullable=False),
    sa.Column('manual_date', sa.Date(), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('bank_input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('match_confidence', sa.String(length=20), nullable=False),
    sa.Column('linkage_status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'source_row')
    )
    op.create_index(op.f('ix_historical_records_source_bank'), 'historical_records', ['source_bank'], unique=False)
    op.create_index(op.f('ix_historical_records_transaction_id'), 'historical_records', ['transaction_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_records_transaction_id'), table_name='historical_records')
    op.drop_index(op.f('ix_historical_records_source_bank'), table_name='historical_records')
    op.drop_table('historical_records')
    # ### end Alembic commands ###
